name: Embedded Benchmark
on:
  workflow_dispatch:
    inputs:
      ITERATIONS:
        description: 'Test iterations, default 3'
        required: false
      PARQUETS:
        description: 'Parquet dataset 1-99, default 1'
        required: false

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        DBNAME: [ "chdb", "duckdb" ]
  
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Benchmark ${{ matrix.DBNAME }}
      env:
        ITERATIONS: ${{ github.event.inputs.ITERATIONS || 3 }}
        PARQUETS: ${{ github.event.inputs.PARQUETS || 1 }}
        DBNAME: ${{ matrix.DBNAME }}
      run: |
        cd ${{ matrix.DBNAME }}
        ./benchmark.sh

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        pull: '--no-edit'

  report:
    needs: benchmark
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Pull latest
      run: git pull --no-edit
    - name: Generate Results
      run: |
        ./generate-results.sh
        mkdir public
        cp index.html public/

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions

    - name: Setup Pages
      if: false
      uses: actions/configure-pages@v3
    - name: Upload artifact
      if: false
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'public'
    - name: Deploy to GitHub Pages
      if: false
      id: deployment
      uses: actions/deploy-pages@v2
