name: Embedded Benchmark
on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        DBNAME: [ "chdb", "duckdb"]
  
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Benchmark ${{ matrix.DBNAME }}
      env:
        ITERATIONS: ${{ github.event.inputs.ITERATIONS || 3 }}
        DBNAME: ${{ matrix.DBNAME }}
      run: |
        cd ${{ matrix.DBNAME }}
        ./benchmark.sh

    - name: Generate Results
      run: |
        ./generate-results.sh
        mkdir public
        mv index.html public/
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'public'
          
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
